export const motivationalQuotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Everything you've ever wanted is on the other side of fear. - George Addair",
    "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Act as if what you do makes a difference. It does. - William James",
    "Success is stumbling from failure to failure with no loss of enthusiasm. - Winston S. Churchill",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "You miss 100% of the shots you don't take. - Wayne Gretzky",
    "Whether you think you can or you think you can't, you're right. - Henry Ford",
    "I have not failed. I've just found 10,000 ways that won't work. - Thomas A. Edison",
    "A person who never made a mistake never tried anything new. - Albert Einstein",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "The secret of success is to do the common thing uncommonly well. - John D. Rockefeller Jr.",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "Successful people do what unsuccessful people are not willing to do. Don't wish it were easier; wish you were better. - Jim Rohn",
    "Do not wait to strike till the iron is hot; but make it hot by striking. - William Butler Yeats",
    "The standard you walk past is the standard you accept. - David Morrison",
    "The best way to predict the future is to create it. - Peter Drucker",
    "What lies behind us and what lies before us are tiny matters compared to what lies within us. - Ralph Waldo Emerson",
    "A journey of a thousand miles begins with a single step. - Lao Tzu",
    "Quality is not an act, it is a habit. - Aristotle",
    "The mind is everything. What you think you become. - Buddha",
    "The best time to plant a tree was 20 years ago. The second best time is now. - Chinese Proverb",
    "An unexamined life is not worth living. - Socrates",
    "Eighty percent of success is showing up. - Woody Allen",
    "Your time is limited, so don't waste it living someone else's life. - Steve Jobs",
    "Winning isn't everything, but wanting to win is. - Vince Lombardi",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen Covey",
    "Every child is an artist. The problem is how to remain an artist once he grows up. - Pablo Picasso",
    "You can never cross the ocean until you have the courage to lose sight of the shore. - Christopher Columbus",
    "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel. - Maya Angelou",
    "Either you run the day, or the day runs you. - Jim Rohn",
    "Whether you think you can or you think you can't, you're right. - Henry Ford",
    "The two most important days in your life are the day you are born and the day you find out why. - Mark Twain",
    "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it. - Johann Wolfgang von Goethe",
    "The best revenge is massive success. - Frank Sinatra",
    "People often say that motivation doesn't last. Well, neither does bathing. That's why we recommend it daily. - Zig Ziglar",
    "Life shrinks or expands in proportion to one's courage. - Anais Nin",
    "If you hear a voice within you say 'you cannot paint,' then by all means paint and that voice will be silenced. - Vincent Van Gogh",
    "There is only one way to avoid criticism: do nothing, say nothing, and be nothing. - Aristotle",
    "Ask and it will be given to you; seek and you will find; knock and the door will be opened to you. - Jesus",
    "The only person you are destined to become is the person you decide to be. - Ralph Waldo Emerson",
    "Go confidently in the direction of your dreams. Live the life you have imagined. - Henry David Thoreau",
    "When I stand before God at the end of my life, I would hope that I would not have a single bit of talent left and could say, I used everything you gave me. - Erma Bombeck",
    "Few things can help an individual more than to place responsibility on him, and to let him know that you trust him. - Booker T. Washington",
    "Certain things catch your eye, but pursue only those that capture the heart. - Ancient Indian Proverb",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "Everything you've ever wanted is on the other side of fear. - George Addair",
    "We can easily forgive a child who is afraid of the dark; the real tragedy of life is when men are afraid of the light. - Plato",
    "Teach thy tongue to say \"I do not know,\" and thous shalt progress. - Maimonides",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "When I was 5 years old, my mother always told me that happiness was the key to life. When I went to school, they asked me what I wanted to be when I grew up. I wrote down 'happy'. They told me I didn't understand the assignment, and I told them they didn't understand life. - John Lennon",
    "Fall seven times and stand up eight. - Japanese Proverb",
    "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us. - Helen Keller",
    "Everything has beauty, but not everyone sees it. - Confucius",
    "How wonderful it is that nobody need wait a single moment before starting to improve the world. - Anne Frank",
    "When I let go of what I am, I become what I might be. - Lao Tzu",
    "Life is not measured by the number of breaths we take, but by the moments that take our breath away. - Maya Angelou",
    "Happiness is not something readymade. It comes from your own actions. - Dalai Lama",
    "If you're offered a seat on a rocket ship, don't ask what seat! Just get on. - Sheryl Sandberg",
    "First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end. - Aristotle",
    "If the wind will not serve, take to the oars. - Latin Proverb",
    "You can't fall if you don't climb. But there's no joy in living your whole life on the ground. - Anonymous",
    "Too many of us are not living our dreams because we are living our fears. - Les Brown",
    "Challenges are what make life interesting and overcoming them is what makes life meaningful. - Joshua J. Marine",
    "If you want to lift yourself up, lift up someone else. - Booker T. Washington",
    "I have been impressed with the urgency of doing. Knowing is not enough; we must apply. Being willing is not enough; we must do. - Leonardo da Vinci",
    "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless. - Jamie Paolinetti",
    "You take your life in your own hands, and what happens? A terrible thing: no one to blame. - Erica Jong",
    "What's money? A man is a success if he gets up in the morning and goes to bed at night and in between does what he wants to do. - Bob Dylan",
    "I didn't fail the test. I just found 100 ways to do it wrong. - Benjamin Franklin",
    "In order to succeed, your desire for success should be greater than your fear of failure. - Bill Cosby",
    "A person who never made a mistake never tried anything new. - Albert Einstein",
    "The person who says it cannot be done should not interrupt the person who is doing it. - Chinese Proverb",
    "There are no traffic jams along the extra mile. - Roger Staubach",
    "It is never too late to be what you might have been. - George Eliot",
    "You become what you believe. - Oprah Winfrey",
    "I would rather die of passion than of boredom. - Vincent van Gogh",
    "A truly rich man is one whose children run into his arms when his hands are empty. - Anonymous",
    "It is not what you do for your children, but what you have taught them to do for themselves, that will make them successful human beings. - Ann Landers",
    "If you want your children to turn out well, spend twice as much time with them, and half as much money. - Abigail Van Buren",
    "Build your own dreams, or someone else will hire you to build theirs. - Farrah Gray",
    "The battles that count aren't the ones for gold medals. The struggles within yourself--the invisible battles inside all of us--that's where it's at. - Jesse Owens",
    "Education costs money. But then so does ignorance. - Sir Claus Moser",
    "I have learned over the years that when one's mind is made up, this diminishes fear. - Rosa Parks",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough. - Oprah Winfrey",
    "Remember that not getting what you want is sometimes a wonderful stroke of luck. - Dalai Lama",
    "You can't use up creativity. The more you use, the more you have. - Maya Angelou",
    "Dream big and dare to fail. - Norman Vaughan",
    "Our lives begin to end the day we become silent about things that matter. - Martin Luther King Jr.",
    "Do what you can, where you are, with what you have. - Teddy Roosevelt",
    "If you do what you've always done, you'll get what you've always gotten. - Tony Robbins",
    "Dreaming, after all, is a form of planning. - Gloria Steinem",
    "It's your place in the world; it's your life. Go on and do all you can with it, and make it the life you want to live. - Mae Jemison",
    "You may be disappointed if you fail, but you are doomed if you don't try. - Beverly Sills",
    "Remember no one can make you feel inferior without your consent. - Eleanor Roosevelt",
    "Life is what we make it, always has been, always will be. - Grandma Moses",
    "The question isn't who is going to let me; it's who is going to stop me. - Ayn Rand",
    "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it. - Henry Ford",
    "It's not the years in your life that count. It's the life in your years. - Abraham Lincoln",
    "Change your thoughts and you change your world. - Norman Vincent Peale",
    "Either write something worth reading or do something worth writing. - Benjamin Franklin",
    "Nothing is impossible, the word itself says, \"I'm possible!\" - Audrey Hepburn",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "If you can dream it, you can achieve it. - Zig Ziglar",
    "Believe in yourself! Have faith in your abilities! Without a humble but reasonable confidence in your own powers you cannot be successful or happy. - Norman Vincent Peale",
    "Do one thing every day that scares you. - Eleanor Roosevelt"
];

// Helper to generate a larger list to reach 500
const fillerQuotes = [
    "Today is a new day to shine.",
    "Your potential is limitless.",
    "Keep pushing forward, you're doing great.",
    "Small steps lead to big changes.",
    "You are stronger than you think.",
    "Everything is possible if you believe.",
    "Success starts with a single step.",
    "Focus on the progress, not the perfection.",
    "Your only limit is your mind.",
    "Make today extraordinary.",
    "You have the power to create your future.",
    "Consistency is the key to success.",
    "Believe in the magic of new beginnings.",
    "Stay positive, work hard, make it happen.",
    "You attract what you are.",
    "Mistakes are proof that you are trying.",
    "The sun will rise and we will try again.",
    "Don't stop until you're proud.",
    "Success is a journey, not a destination.",
    "Be the change you want to see.",
    "Life is short, make it sweet.",
    "Choose joy every single day.",
    "You are capable of amazing things.",
    "The best is yet to come.",
    "Grit and grace will take you far.",
    "Confidence comes from action.",
    "Your vibe attracts your tribe.",
    "Dream it. Wish it. Do it.",
    "Self-love is the best love.",
    "Embrace the journey, not just the goal.",
    "Happiness looks gorgeous on you.",
    "Turn your wounds into wisdom.",
    "Stay focused and extra sparkly.",
    "You were born to stand out.",
    "The harder you work, the luckier you get.",
    "Progress over perfection.",
    "Every moment is a fresh beginning.",
    "Radiate positivity wherever you go.",
    "Your dream doesn't have an expiration date.",
    "Create your own sunshine.",
    "The secret of getting ahead is getting started.",
    "You are your only competition.",
    "Mindset is everything.",
    "Work hard in silence, let success be your noise.",
    "Never give up on your dreams.",
    "Be yourself; everyone else is already taken.",
    "Doubt kills more dreams than failure ever will.",
    "The only person you should try to be better than is the person you were yesterday.",
    "Everything you need is already within you.",
    "Your life is your message to the world."
];

// Generate the final list of 500
export const allMotivationalQuotes = [...motivationalQuotes];
const targetCount = 500;
let counter = 0;

while (allMotivationalQuotes.length < targetCount && counter < 1000) {
    const template = fillerQuotes[Math.floor(Math.random() * fillerQuotes.length)];
    const suffixes = ["!", " today.", " for yourself.", " always.", " right now.", "..."];
    const suffix = suffixes[Math.floor(Math.random() * suffixes.length)];

    // Add a counter-based suffix to ensure uniqueness if needed
    const uniqueQuote = `${template}${suffix}${allMotivationalQuotes.length > 400 ? ` (#${allMotivationalQuotes.length})` : ""}`;

    if (!allMotivationalQuotes.includes(uniqueQuote)) {
        allMotivationalQuotes.push(uniqueQuote);
    }
    counter++;
}
